// Auto-generated from source-data/cc menu.xlsx
// Update the Excel file, then run npm run generate-menu before publishing.
const CATEGORIES = {
  "soups": {
    "tr": "Çorbalar",
    "en": "Soups",
    "ja": "スープ",
    "ja_latn": "Suupu"
  },
  "salads": {
    "tr": "Salatalar",
    "en": "Salads",
    "ja": "サラダ",
    "ja_latn": "Sarada"
  },
  "meze": {
    "tr": "Mezeler",
    "en": "Meze",
    "ja": "前菜",
    "ja_latn": "Meze"
  },
  "oliveOil": {
    "tr": "Zeytinyağlılar",
    "en": "Olive Oil Dishes",
    "ja": "オリーブオイル料理",
    "ja_latn": "oriibuoiru"
  },
  "hotStarters": {
    "tr": "Ara Sıcaklar",
    "en": "Hot Starters",
    "ja": "温かい前菜",
    "ja_latn": "kai"
  },
  "burgers": {
    "tr": "Burgerler",
    "en": "Burgers",
    "ja": "バーガー",
    "ja_latn": "baagaa"
  },
  "mainCourses": {
    "tr": "Ana Yemekler",
    "en": "Main Courses",
    "ja": "メイン料理",
    "ja_latn": "mein"
  },
  "special": {
    "tr": "Special",
    "en": "Specials",
    "ja": "スペシャル",
    "ja_latn": "supesharu"
  },
  "pizza": {
    "tr": "Pizzalar",
    "en": "Pizzas",
    "ja": "ピザ",
    "ja_latn": "Piza"
  },
  "pideLahmacun": {
    "tr": "Pide-Lahmacun",
    "en": "Pide & Lahmacun",
    "ja": "ピデ・ラフマジュン",
    "ja_latn": "piderafumajun"
  },
  "pasta": {
    "tr": "Makarnalar",
    "en": "Pasta",
    "ja": "パスタ",
    "ja_latn": "Pasuta"
  },
  "desserts": {
    "tr": "Tatlılar",
    "en": "Desserts",
    "ja": "デザート",
    "ja_latn": "Dezāto"
  },
  "breakfast": {
    "tr": "Kahvaltılar",
    "en": "Breakfast",
    "ja": "朝食",
    "ja_latn": "Asagohan"
  },
  "nuts": {
    "tr": "Kuru Yemişler",
    "en": "Nuts & Dried Fruits",
    "ja": "ナッツ類",
    "ja_latn": "nattsu"
  },
  "hotDrinks": {
    "tr": "Sıcak İçecekler",
    "en": "Hot Drinks",
    "ja": "温かい飲み物",
    "ja_latn": "kaimi"
  },
  "coldDrinks": {
    "tr": "Soğuk İçecekler",
    "en": "Cold Drinks",
    "ja": "冷たい飲み物",
    "ja_latn": "taimi"
  },
  "beers": {
    "tr": "Biralar",
    "en": "Beers",
    "ja": "ビール",
    "ja_latn": "biiru"
  },
  "spirits": {
    "tr": "Alkollü İçecekler",
    "en": "Spirits",
    "ja": "蒸留酒",
    "ja_latn": "Spirits"
  },
  "wines": {
    "tr": "Şaraplar",
    "en": "Wines",
    "ja": "ワイン",
    "ja_latn": "wain"
  },
  "whiskies": {
    "tr": "Viskiler",
    "en": "Whiskies",
    "ja": "ウイスキー",
    "ja_latn": "uisukii"
  }
};
const CATEGORY_ORDER = [
  "soups",
  "salads",
  "meze",
  "oliveOil",
  "hotStarters",
  "burgers",
  "mainCourses",
  "special",
  "pizza",
  "pideLahmacun",
  "pasta",
  "desserts",
  "breakfast",
  "nuts",
  "hotDrinks",
  "coldDrinks",
  "beers",
  "spirits",
  "wines",
  "whiskies"
];
const MENU_ITEMS = [
  { id: 2135, category: 'spirits', name: { tr: "Tekirdağ Rakısı Altın Seri35 cl", en: "Tekirdağ Rakı Gold Series 35 cl", ja: "テキルダー・ラク ゴールドシリーズ 35センチリットル", ja_latn: "Tekirudaa Rakushu Gorudo Shirizu 35 Sentorittoru" }, price: 1149, photo: "Tekirdağ Rakısı Altın Seri35 cl", ingredients: "" },
  { id: 2136, category: 'spirits', name: { tr: "Tekirdağ Rakısı Altın Seri15 cl", en: "Tekirdağ Rakı Gold Series 15 cl", ja: "テキルダー・ラク ゴールドシリーズ 15センチリットル", ja_latn: "Tekirudaa Rakushu Gorudo Shirizu 15 Sentorittoru" }, price: 540, photo: "Tekirdağ Rakısı Altın Seri15 cl", ingredients: "" },
  { id: 2137, category: 'spirits', name: { tr: "Beylerbeyi Göbek Rakısı 35 cl", en: "Beylerbeyi Göbek Rakı 35 cl", ja: "ベイレルベイ・ギョベク・ラク 35センチリットル", ja_latn: "Beirerubei Gobeku Rakushu 35 Sentorittoru" }, price: 1343.5, photo: "Beylerbeyi Göbek Rakısı 35 cl", ingredients: "" },
  { id: 2145, category: 'spirits', name: { tr: "Tekirdağ Rakısı Altın Seri Duble", en: "Tekirdağ Rakı Gold Series Double", ja: "テキルダー・ラク ゴールドシリーズ ダブル", ja_latn: "Tekirudaa Rakushu Gorudo Shirizu Daburu" }, price: 270, photo: "Tekirdağ Rakısı Altın Seri Duble", ingredients: "" },
  { id: 2146, category: 'spirits', name: { tr: "Tekirdağ Rakısı Altın Seri Tek", en: "Tekirdağ Rakı Gold Series Single", ja: "テキルダー・ラク ゴールドシリーズ シングル", ja_latn: "Tekirudaa Rakushu Gorudo Shirizu Shinguru" }, price: 134, photo: "Tekirdağ Rakısı Altın Seri Tek", ingredients: "" },
  { id: 2153, category: 'spirits', name: { tr: "Yeni Rakı Yeni Seri 35 cl", en: "Yeni Rakı New Series 35 cl", ja: "イェニ・ラク ニューシリーズ 35センチリットル", ja_latn: "Yeni Raku Shin Shirizu 35 Sentorittoru" }, price: 1040.5, photo: "Yeni Rakı Yeni Seri 35 cl", ingredients: "" },
  { id: 2154, category: 'spirits', name: { tr: "Yeni Rakı Yeni Seri Duble", en: "Yeni Rakı New Series Double", ja: "イェニ・ラク ニューシリーズ ダブル", ja_latn: "Yeni Raku Shin Shirizu Daburu" }, price: 232, photo: "Yeni Rakı Yeni Seri Duble", ingredients: "" },
  { id: 2159, category: 'spirits', name: { tr: "Yeni Rakı Yeni Seri Tek", en: "Yeni Rakı New Series Single", ja: "イェニ・ラク ニューシリーズ シングル", ja_latn: "Yeni Raku Shin Shirizu Shinguru" }, price: 116.5, photo: "Yeni Rakı Yeni Seri Tek", ingredients: "" },
  { id: 2162, category: 'spirits', name: { tr: "Tekirdağ Rakısı Altın Seri 50 cl", en: "Tekirdağ Rakı Gold Series 50 cl", ja: "テキルダー・ラク ゴールドシリーズ 50センチリットル", ja_latn: "Tekirudaa Rakushu Gorudo Shirizu 50 Sentorittoru" }, price: 1532, photo: "Tekirdağ Rakısı Altın Seri 50 cl", ingredients: "" },
  { id: 2164, category: 'spirits', name: { tr: "Yeni Rakı Yeni Seri 15 cl", en: "Yeni Rakı New Series 15 cl", ja: "イェニ・ラク ニューシリーズ 15センチリットル", ja_latn: "Yeni Raku Shin Shirizu 15 Sentorittoru" }, price: 462.5, photo: "Yeni Rakı Yeni Seri 15 cl", ingredients: "" },
  { id: 2167, category: 'spirits', name: { tr: "Yeni Rakı Yeni Seri 50 cl", en: "Yeni Rakı New Series 50 cl", ja: "イェニ・ラク ニューシリーズ 50センチリットル", ja_latn: "Yeni Raku Shin Shirizu 50 Sentorittoru" }, price: 1422.5, photo: "Yeni Rakı Yeni Seri 50 cl", ingredients: "" },
  { id: 2169, category: 'spirits', name: { tr: "Absolut Vodka Tek", en: "Absolut Vodka Single", ja: "アブソルート・ウォッカ シングル", ja_latn: "Abusoryuto Vodoka Shinguru" }, price: 119, photo: "Absolut Vodka Tek", ingredients: "" },
  { id: 2175, category: 'spirits', name: { tr: "Tekirdağ Rakısı Altın Seri  70 cl", en: "Tekirdağ Rakı Gold Series 70 cl", ja: "テキルダー・ラク ゴールドシリーズ 70センチリットル", ja_latn: "Tekirudaa Rakushu Gorudo Shirizu 70 Sentorittoru" }, price: 1978, photo: "Tekirdağ Rakısı Altın Seri  70 cl", ingredients: "" },
  { id: 2177, category: 'spirits', name: { tr: "Yeni Rakı Yeni Seri 70 cl", en: "Yeni Rakı New Series 70 cl", ja: "イェニ・ラク ニューシリーズ 70センチリットル", ja_latn: "Yeni Raku Shin Shirizu 70 Sentorittoru" }, price: 1851.5, photo: "Yeni Rakı Yeni Seri 70 cl", ingredients: "" },
  { id: 2179, category: 'spirits', name: { tr: "Absolut Vodka 35 cl", en: "Absolut Vodka 35 cl", ja: "アブソルート・ウォッカ 35センチリットル", ja_latn: "Abusoryuto Vodoka 35 Sentorittoru" }, price: 1040.75, photo: "Absolut Vodka 35 cl", ingredients: "" },
  { id: 2180, category: 'spirits', name: { tr: "Absolut Vodka Duble", en: "Absolut Vodka Double", ja: "アブソルート・ウォッカ ダブル", ja_latn: "Abusoryuto Vodoka Daburu" }, price: 238, photo: "Absolut Vodka Duble", ingredients: "" },
  { id: 2181, category: 'spirits', name: { tr: "Beylerbeyi Göbek Rakısı 70 cl", en: "Beylerbeyi Göbek Rakı 70 cl", ja: "ベイレルベイ・ギョベク・ラク 70センチリットル", ja_latn: "Beirerubei Gobeku Rakushu 70 Sentorittoru" }, price: 2370, photo: "Beylerbeyi Göbek Rakısı 70 cl", ingredients: "" },
  { id: 2182, category: 'spirits', name: { tr: "Beylerbeyi Göbek Rakısı 50 cl", en: "Beylerbeyi Göbek Rakı 50 cl", ja: "ベイレルベイ・ギョベク・ラク 50センチリットル", ja_latn: "Beirerubei Gobeku Rakushu 50 Sentorittoru" }, price: 1829, photo: "Beylerbeyi Göbek Rakısı 50 cl", ingredients: "" },
  { id: 2184, category: 'spirits', name: { tr: "İstanblue Vodka 15 cl", en: "İstanblue Vodka 15 cl", ja: "イスタンブルー・ウォッカ 15センチリットル", ja_latn: "Isutanburu Vodoka 15 Sentorittoru" }, price: 322, photo: "İstanblue Vodka 15 cl", ingredients: "" },
  { id: 2185, category: 'spirits', name: { tr: "İstanblue Vodka Tek", en: "İstanblue Vodka Single", ja: "イスタンブルー・ウォッカ シングル", ja_latn: "Isutanburu Vodoka Shinguru" }, price: 80.5, photo: "İstanblue Vodka Tek", ingredients: "" },
  { id: 2188, category: 'spirits', name: { tr: "Absolut Vodka 15 cl", en: "Absolut Vodka 15 cl", ja: "アブソルート・ウォッカ 15センチリットル", ja_latn: "Abusoryuto Vodoka 15 Sentorittoru" }, price: 431.5, photo: "Absolut Vodka 15 cl", ingredients: "" },
  { id: 2190, category: 'spirits', name: { tr: "İstanblue Vodka 35 cl", en: "İstanblue Vodka 35 cl", ja: "イスタンブルー・ウォッカ 35センチリットル", ja_latn: "Isutanburu Vodoka 35 Sentorittoru" }, price: 1041, photo: "İstanblue Vodka 35 cl", ingredients: "" },
  { id: 2196, category: 'spirits', name: { tr: "İstanblue Vodka Duble", en: "İstanblue Vodka Double", ja: "イスタンブルー・ウォッカ ダブル", ja_latn: "Isutanburu Vodoka Daburu" }, price: 146.5, photo: "İstanblue Vodka Duble", ingredients: "" },
  { id: 2201, category: 'spirits', name: { tr: "Absolut Vodka 70 cl", en: "Absolut Vodka 70 cl", ja: "アブソルート・ウォッカ 70センチリットル", ja_latn: "Abusoryuto Vodoka 70 Sentorittoru" }, price: 1900, photo: "Absolut Vodka 70 cl", ingredients: "" },
  { id: 2209, category: 'spirits', name: { tr: "İstanblue Vodka 70 cl", en: "İstanblue Vodka 70 cl", ja: "イスタンブルー・ウォッカ 70センチリットル", ja_latn: "Isutanburu Vodoka 70 Sentorittoru" }, price: 1283.5, photo: "İstanblue Vodka 70 cl", ingredients: "" },
  { id: 2214, category: 'spirits', name: { tr: "Nane Likörü 35 cl", en: "Mint Liqueur 35 cl", ja: "ミントリキュール 35センチリットル", ja_latn: "Minto Rikyuru 35 Sentorittoru" }, price: 813.5, photo: "Nane Likörü 35 cl", ingredients: "" },
  { id: 2215, category: 'spirits', name: { tr: "Nane Likörü Bardak 4 cl", en: "Glass of Mint Liqueur 4 cl", ja: "ミントリキュール グラス 4センチリットル", ja_latn: "Minto Rikyuru Garasu 4 Sentorittoru" }, price: 136, photo: "Nane Likörü Bardak 4 cl", ingredients: "" },
  { id: 2250, category: 'spirits', name: { tr: "Beylerbeyi Göbek Rakısı 15 cl", en: "Beylerbeyi Göbek Rakı 15 cl", ja: "ベイレルベイ ギョベック ラク 15cl", ja_latn: "Beirerubei Göbekku Rakı 15 cl" }, price: 508.5, photo: "Beylerbeyi Göbek Rakısı 15 cl", ingredients: "" },
  { id: 2251, category: 'spirits', name: { tr: "Beylerbeyi Göbek Rakısı Duble", en: "Beylerbeyi Göbek Rakı Double", ja: "ベイレルベイ ギョベック ラク ダブル", ja_latn: "Beirerubei Göbekku Rakı Daburu" }, price: 253.5, photo: "Beylerbeyi Göbek Rakısı Duble", ingredients: "" },
  { id: 2252, category: 'spirits', name: { tr: "Beylerbeyi Göbek Rakısı Tek", en: "Beylerbeyi Göbek Rakı Single", ja: "ベイレルベイ ギョベック ラク シングル", ja_latn: "Beirerubei Göbekku Rakı Shinguru" }, price: 127.5, photo: "Beylerbeyi Göbek Rakısı Tek", ingredients: "" },
  { id: 2019, category: 'mainCourses', name: { tr: "Karışık Izgara", en: "Mixed Grill", ja: "ミックスグリル", ja_latn: "Mikkusu Guriru" }, price: 493.5, photo: "Karışık Izgara", ingredients: "" },
  { id: 2030, category: 'mainCourses', name: { tr: "Tavuk Izgara", en: "Grilled Chicken", ja: "グリルチキン", ja_latn: "Guriru Chikin" }, price: 142, photo: "Tavuk Izgara", ingredients: "" },
  { id: 2039, category: 'mainCourses', name: { tr: "Izgara Köfte Klasik", en: "Classic Grilled Meatballs", ja: "クラシック・グリルキョフテ", ja_latn: "Kurashikku Guriru Kofte" }, price: 260, photo: "Izgara Köfte Klasik", ingredients: "" },
  { id: 2041, category: 'mainCourses', name: { tr: "Tavuk Şiş Izgara", en: "Grilled Chicken Skewers", ja: "グリルチキン串", ja_latn: "Guriru Chikin Shish" }, price: 133, photo: "Tavuk Şiş Izgara", ingredients: "" },
  { id: 2046, category: 'mainCourses', name: { tr: "Güveçte Yaprak Kavurma", en: "Sautéed Meat with Vine Leaves in a Casserole", ja: "土鍋の葉包み肉炒め", ja_latn: "Donabe no Happa Niku Itame" }, price: 509.5, photo: "Güveçte Yaprak Kavurma", ingredients: "" },
  { id: 2049, category: 'mainCourses', name: { tr: "Adana Kebab Acılı", en: "Spicy Adana Kebab", ja: "辛口アダナケバブ", ja_latn: "Karai Adana Kebabu" }, price: 325, photo: "Adana Kebab Acılı", ingredients: "" },
  { id: 2052, category: 'mainCourses', name: { tr: "Beyti Kebab", en: "Beyti Kebab", ja: "ベイティケバブ", ja_latn: "Beiti Kebabu" }, price: 370, photo: "Beyti Kebab", ingredients: "" },
  { id: 2054, category: 'mainCourses', name: { tr: "Düğün Kavurma", en: "Wedding-Style Roasted Meat", ja: "結婚式風肉炒め", ja_latn: "Kekkonshiki-fu Niku Itame" }, price: 285, photo: "Düğün Kavurma", ingredients: "" },
  { id: 2056, category: 'mainCourses', name: { tr: "Güveçte Kaşarlı Köfte", en: "Meatballs with Cheese in a Casserole", ja: "土鍋チーズキョフテ", ja_latn: "Donabe no Chizu Kofte" }, price: 380, photo: "Güveçte Kaşarlı Köfte", ingredients: "" },
  { id: 2065, category: 'mainCourses', name: { tr: "Bonfile Izgara", en: "Grilled Tenderloin", ja: "グリルヒレ肉", ja_latn: "Guriru Hire" }, price: 482, photo: "Bonfile Izgara", ingredients: "" },
  { id: 2093, category: 'mainCourses', name: { tr: "Kuzu Şiş", en: "Lamb Skewers", ja: "ラム串焼き", ja_latn: "Kohitsuji Shish" }, price: 365, photo: "Kuzu Şiş", ingredients: "" },
  { id: 2100, category: 'mainCourses', name: { tr: "Kuzu Pirzola", en: "Lamb Chops", ja: "ラムチョップ", ja_latn: "Ramu Choppu" }, price: 696, photo: "Kuzu Pirzola", ingredients: "" },
  { id: 2107, category: 'mainCourses', name: { tr: "Urfa Kebab Acısız", en: "Mild Urfa Kebab", ja: "辛くないウルファケバブ", ja_latn: "Karaku Nai Urufa Kebabu" }, price: 331, photo: "Urfa Kebab Acısız", ingredients: "" },
  { id: 2110, category: 'mainCourses', name: { tr: "Güveçte Piliç Kavurma", en: "Chicken Sauté in a Casserole", ja: "土鍋チキン炒め", ja_latn: "Donabe no Chikin Itame" }, price: 174.5, photo: "Güveçte Piliç Kavurma", ingredients: "" },
  { id: 2111, category: 'mainCourses', name: { tr: "Güveçte Çoban Kavurma", en: "Shepherd-Style Meat Sauté in a Casserole", ja: "土鍋チョバン肉炒め", ja_latn: "Donabe no Choban Niku Itame" }, price: 491, photo: "Güveçte Çoban Kavurma", ingredients: "" },
  { id: 2017, category: 'hotStarters', name: { tr: "Paçanga Böreği", en: "Paçanga Pastry", ja: "パチャンガ・ボレキ", ja_latn: "Pachanga Boregi" }, price: 142.5, photo: "Paçanga Böreği", ingredients: "" },
  { id: 2020, category: 'hotStarters', name: { tr: "Patates Kızartması", en: "French Fries", ja: "フライドポテト", ja_latn: "Furaido Poteto" }, price: 45, photo: "Patates Kızartması", ingredients: "" },
  { id: 2024, category: 'hotStarters', name: { tr: "İçli Köfte", en: "Stuffed Meatballs", ja: "イチリ・キョフテ", ja_latn: "Ichiri Kofte" }, price: 99.5, photo: "İçli Köfte", ingredients: "" },
  { id: 2026, category: 'hotStarters', name: { tr: "Baharatlı Patates Kızartma", en: "Spicy French Fries", ja: "スパイシーフライドポテト", ja_latn: "Supaisi Furaido Poteto" }, price: 46, photo: "Baharatlı Patates Kızartma", ingredients: "" },
  { id: 2048, category: 'hotStarters', name: { tr: "Mantar Güveç", en: "Mushroom Casserole", ja: "キノコの土鍋焼き", ja_latn: "Kinoko no Donabe-yaki" }, price: 110, photo: "Mantar Güveç", ingredients: "" },
  { id: 2076, category: 'hotStarters', name: { tr: "Soğan Kroket", en: "Onion Croquettes", ja: "オニオンコロッケ", ja_latn: "Onion Kuroketto" }, price: 30.75, photo: "Soğan Kroket", ingredients: "" },
  { id: 2092, category: 'hotStarters', name: { tr: "Pirinç Pilavı", en: "Rice Pilaf", ja: "ライスピラフ", ja_latn: "Raisu Pirafu" }, price: 33, photo: "Pirinç Pilavı", ingredients: "" },
  { id: 1683, category: 'hotStarters', name: { tr: "Kaşarpane", en: "Kaşarpane", ja: "カシャルパネ", ja_latn: "Kasharupane" }, price: 71, photo: "Kaşarpane", ingredients: "" },
  { id: 2125, category: 'hotStarters', name: { tr: "Patates Kroket", en: "Potato Croquettes", ja: "ポテトコロッケ", ja_latn: "Poteto Kuroketto" }, price: 39.25, photo: "Patates Kroket", ingredients: "" },
  { id: 2277, category: 'hotStarters', name: { tr: "Sosis Tava", en: "Pan-Fried Sausage", ja: "フライパンソーセージ", ja_latn: "Furaipan Soseji" }, price: 104.5, photo: "Sosis Tava", ingredients: "" },
  { id: 2059, category: 'beers', name: { tr: "Tuborg Şişe Bira 500 ml", en: "Tuborg Bottled Beer 500 ml", ja: "ツボルグ 瓶ビール 500ミリリットル", ja_latn: "Tuborugu Bin Biru 500 Miririttoru" }, price: 130, photo: "Tuborg Şişe Bira 500 ml", ingredients: "" },
  { id: 2061, category: 'beers', name: { tr: "Bomonti Şişe Bira Filtresiz 500 ml", en: "Bomonti Unfiltered Bottled Beer 500 ml", ja: "ボモンティ 無濾過瓶ビール 500ミリリットル", ja_latn: "Bomonti Muroka Bin Biru 500 Miririttoru" }, price: 154.5, photo: "Bomonti Şişe Bira Filtresiz 500 ml", ingredients: "" },
  { id: 2087, category: 'beers', name: { tr: "Efes Şişe Bira 500 ml", en: "Efes Bottled Beer 500 ml", ja: "エフェス 瓶ビール 500ミリリットル", ja_latn: "Efesu Bin Biru 500 Miririttoru" }, price: 138.5, photo: "Efes Şişe Bira 500 ml", ingredients: "" },
  { id: 2118, category: 'beers', name: { tr: "Carlsberg Şişe Bira 330 ml", en: "Carlsberg Bottled Beer 330 ml", ja: "カールスバーグ 瓶ビール 330ミリリットル", ja_latn: "Karusuberugu Bin Biru 330 Miririttoru" }, price: 112.5, photo: "Carlsberg Şişe Bira 330 ml", ingredients: "" },
  { id: 2122, category: 'beers', name: { tr: "Miller Şişe Bira 330 ml", en: "Miller Bottled Beer 330 ml", ja: "ミラー 瓶ビール 330ミリリットル", ja_latn: "Mira Bin Biru 330 Miririttoru" }, price: 121, photo: "Miller Şişe Bira 330 ml", ingredients: "" },
  { id: 2158, category: 'beers', name: { tr: "Efes Glutensiz Bira 500 ml", en: "Efes Gluten-Free Beer 500 ml", ja: "エフェス グルテンフリービール 500ミリリットル", ja_latn: "Efesu Guruten Furi Biru 500 Miririttoru" }, price: 161.5, photo: "Efes Glutensiz Bira 500 ml", ingredients: "" },
  { id: 2035, category: 'burgers', name: { tr: "Lexus Burger", en: "Lexus Burger", ja: "レクサス・バーガー", ja_latn: "Rekusasu Baga" }, price: 385, photo: "Lexus Burger", ingredients: "" },
  { id: 2053, category: 'burgers', name: { tr: "Corolla Burger King", en: "Corolla Burger King", ja: "カローラ・バーガーキング", ja_latn: "Karora Baga Kingu" }, price: 320, photo: "Corolla Burger King", ingredients: "" },
  { id: 2091, category: 'burgers', name: { tr: "İkiz Burger Cup", en: "Twin Burger Cup", ja: "ツインバーガーカップ", ja_latn: "Futago Baga Kappu" }, price: 273.5, photo: "İkiz Burger Cup", ingredients: "" },
  { id: 2025, category: 'soups', name: { tr: "Günün Çorbası", en: "Soup of the Day", ja: "本日のスープ", ja_latn: "Honjitsu no Supu" }, price: 60, photo: "Günün Çorbası", ingredients: "" },
  { id: 2074, category: 'breakfast', name: { tr: "Serpme Kahvaltı 2 Kişilik", en: "Turkish Breakfast for 2", ja: "2名様用トルコ式朝食", ja_latn: "Futari-yo Asagohan Setto" }, price: 553, photo: "Serpme Kahvaltı 2 Kişilik", ingredients: "" },
  { id: 1659, category: 'breakfast', name: { tr: "Menemen", en: "Menemen", ja: "メネメン", ja_latn: "Menemen" }, price: 66, photo: "Menemen", ingredients: "" },
  { id: 2086, category: 'breakfast', name: { tr: "Kahvaltı Tabağı 1 Kişilik", en: "Breakfast Plate for 1", ja: "1名様用朝食プレート", ja_latn: "Hitori-yo Asagohan Pureto" }, price: 166, photo: "Kahvaltı Tabağı 1 Kişilik", ingredients: "" },
  { id: 2098, category: 'breakfast', name: { tr: "Beyaz Peynir Kahvaltılık-Ezine", en: "Ezine White Cheese for Breakfast", ja: "エジネ産ホワイトチーズ", ja_latn: "Asagohan-yo Shiro Chizu Ezine" }, price: 37, photo: "Beyaz Peynir Kahvaltılık-Ezine", ingredients: "" },
  { id: 2116, category: 'breakfast', name: { tr: "Çocuk Kahvaltı Tabağı", en: "Children's Breakfast Plate", ja: "お子様朝食プレート", ja_latn: "Kodomo Asagohan Pureto" }, price: 133, photo: "Çocuk Kahvaltı Tabağı", ingredients: "" },
  { id: 2117, category: 'breakfast', name: { tr: "Tereyağlı Tavada Sucuklu Yumurta", en: "Fried Eggs with Sausage and Butter", ja: "バター焼きソーセージエッグ", ja_latn: "Bata Yaki Soseji Tamago" }, price: 129, photo: "Tereyağlı Tavada Sucuklu Yumurta", ingredients: "" },
  { id: 2120, category: 'breakfast', name: { tr: "Haşlama Yumurta", en: "Boiled Egg", ja: "ゆで卵", ja_latn: "Yude Tamago" }, price: 13.245, photo: "Haşlama Yumurta", ingredients: "" },
  { id: 2130, category: 'breakfast', name: { tr: "Bal Kaymak Kahvaltılık", en: "Honey and Clotted Cream", ja: "ハチミツとカイマク", ja_latn: "Hachimitsu to Kaymaku" }, price: 48.5, photo: "Bal Kaymak Kahvaltılık", ingredients: "" },
  { id: 2132, category: 'breakfast', name: { tr: "Çikolata Kahvaltılık", en: "Chocolate Spread for Breakfast", ja: "朝食用チョコレート", ja_latn: "Asagohan-yo Chokoreto" }, price: 22.5, photo: "Çikolata Kahvaltılık", ingredients: "" },
  { id: 2139, category: 'breakfast', name: { tr: "Omlet Kaşarlı", en: "Cheese Omelette", ja: "チーズオムレツ", ja_latn: "Chizu Omuretsu" }, price: 142, photo: "Omlet Kaşarlı", ingredients: "" },
  { id: 2140, category: 'breakfast', name: { tr: "Kaşar Peynir Kahvaltılık", en: "Kashar Cheese for Breakfast", ja: "朝食用カシャールチーズ", ja_latn: "Asagohan-yo Kasharu Chizu" }, price: 31.25, photo: "Kaşar Peynir Kahvaltılık", ingredients: "" },
  { id: 2141, category: 'breakfast', name: { tr: "Tereyağlı Tavada Sade Yumurta", en: "Plain Fried Eggs with Butter", ja: "バター焼きプレーンエッグ", ja_latn: "Bata Yaki Puren Tamago" }, price: 46, photo: "Tereyağlı Tavada Sade Yumurta", ingredients: "" },
  { id: 2144, category: 'breakfast', name: { tr: "Zeytin Kahvaltılık Yeşil-Siyah", en: "Green and Black Olives for Breakfast", ja: "朝食用グリーン・ブラックオリーブ", ja_latn: "Asagohan-yo Midori to Kuro no Oribu" }, price: 12.25, photo: "Zeytin Kahvaltılık Yeşil-Siyah", ingredients: "" },
  { id: 2170, category: 'breakfast', name: { tr: "Omlet Karışık", en: "Mixed Omelette", ja: "ミックスオムレツ", ja_latn: "Mikkusu Omuretsu" }, price: 201, photo: "Omlet Karışık", ingredients: "" },
  { id: 2174, category: 'breakfast', name: { tr: "Reçel Kahvaltılık", en: "Breakfast Jam", ja: "朝食用ジャム", ja_latn: "Asagohan-yo Jamu" }, price: 16.25, photo: "Reçel Kahvaltılık", ingredients: "" },
  { id: 2176, category: 'breakfast', name: { tr: "Tereyağ Kahvaltılık", en: "Butter for Breakfast", ja: "朝食用バター", ja_latn: "Asagohan-yo Bata" }, price: 25, photo: "Tereyağ Kahvaltılık", ingredients: "" },
  { id: 2304, category: 'breakfast', name: { tr: "Patates Kızartması", en: "French Fries", ja: "フライドポテト", ja_latn: "Furaido Poteto" }, price: 45, photo: "Patates Kızartması", ingredients: "" },
  { id: 2218, category: 'breakfast', name: { tr: "Sosis Tava", en: "Pan-Fried Sausage", ja: "フライパンソーセージ", ja_latn: "Furaipan Soseji" }, price: 184, photo: "Sosis Tava", ingredients: "" },
  { id: 2114, category: 'nuts', name: { tr: "Karışık Kuru Yemiş", en: "Mixed Nuts", ja: "ミックスナッツ", ja_latn: "Mikkusu Nattsu" }, price: 85, photo: "Karışık Kuru Yemiş", ingredients: "" },
  { id: 2142, category: 'nuts', name: { tr: "Tuzlu Yer Fıstığı", en: "Salted Peanuts", ja: "塩味ピーナッツ", ja_latn: "Shioaji Pinattsu" }, price: 43, photo: "Tuzlu Yer Fıstığı", ingredients: "" },
  { id: 2150, category: 'nuts', name: { tr: "Kaju Fıstık", en: "Cashew Nuts", ja: "カシューナッツ", ja_latn: "Kashu Nattsu" }, price: 79.75, photo: "Kaju Fıstık", ingredients: "" },
  { id: 2037, category: 'pasta', name: { tr: "Kremalı Tavuklu Penne", en: "Creamy Chicken Penne", ja: "クリームチキンペンネ", ja_latn: "Kurimu Chikin Penne" }, price: 130, photo: "Kremalı Tavuklu Penne", ingredients: "" },
  { id: 2112, category: 'pasta', name: { tr: "Penne Arabietta Acılı", en: "Spicy Penne Arrabbiata", ja: "辛口ペンネ・アラビアータ", ja_latn: "Karai Penne Arabiata" }, price: 90, photo: "Penne Arabietta Acılı", ingredients: "" },
  { id: 2128, category: 'pasta', name: { tr: "Spagetti Napolitan", en: "Spaghetti Napolitana", ja: "スパゲッティ・ナポリタン", ja_latn: "Supagetti Naporitan" }, price: 76.5, photo: "Spagetti Napolitan", ingredients: "" },
  { id: 2134, category: 'pasta', name: { tr: "Kremalı Spagetti", en: "Creamy Spaghetti", ja: "クリームスパゲッティ", ja_latn: "Kurimu Supagetti" }, price: 108.75, photo: "Kremalı Spagetti", ingredients: "" },
  { id: 2038, category: 'meze', name: { tr: "Kuru Cacık", en: "Thick Cacık", ja: "濃厚ジャジュク", ja_latn: "Koi Jajikku" }, price: 40, photo: "Kuru Cacık", ingredients: "" },
  { id: 1629, category: 'meze', name: { tr: "Haydari", en: "Haydari", ja: "ハイダリ", ja_latn: "Haidari" }, price: 37, photo: "Haydari", ingredients: "" },
  { id: 2064, category: 'meze', name: { tr: "Acılı Antep Ezme", en: "Spicy Antep Ezme", ja: "辛口ガズィアンテプ・エズメ", ja_latn: "Karai Antep Ezume" }, price: 40, photo: "Acılı Antep Ezme", ingredients: "" },
  { id: 2067, category: 'meze', name: { tr: "Girit Ezme", en: "Cretan Ezme", ja: "ギリット・エズメ", ja_latn: "Girito Ezume" }, price: 95, photo: "Girit Ezme", ingredients: "" },
  { id: 1657, category: 'meze', name: { tr: "Humus", en: "Hummus", ja: "フムス", ja_latn: "Humusu" }, price: 40, photo: "Humus", ingredients: "" },
  { id: 2080, category: 'meze', name: { tr: "Patlıcan Soslu", en: "Eggplant with Sauce", ja: "ナスのソース和え", ja_latn: "Nasu no Sosu-ae" }, price: 40.5, photo: "Patlıcan Soslu", ingredients: "" },
  { id: 2097, category: 'meze', name: { tr: "Atom Mancı", en: "Atom Mancı", ja: "アトム・マンジュ", ja_latn: "Atomu Manji" }, price: 50, photo: "Atom Mancı", ingredients: "" },
  { id: 2103, category: 'meze', name: { tr: "Amerikan Salata", en: "American Salad", ja: "アメリカンサラダ", ja_latn: "Amerika Sarada" }, price: 35, photo: "Amerikan Salata", ingredients: "" },
  { id: 2115, category: 'meze', name: { tr: "Ispanak Kavurma", en: "Sautéed Spinach", ja: "ほうれん草炒め", ja_latn: "Horenso Itame" }, price: 39, photo: "Ispanak Kavurma", ingredients: "" },
  { id: 2124, category: 'meze', name: { tr: "Yoğurtlu Semizotu", en: "Purslane with Yogurt", ja: "ヨーグルトとスベリヒユ", ja_latn: "Yoguruto to Suberihiyu" }, price: 54, photo: "Yoğurtlu Semizotu", ingredients: "" },
  { id: 2126, category: 'meze', name: { tr: "Ordövr Tabağı", en: "Hors d'Oeuvres Platter", ja: "オードブル盛り合わせ", ja_latn: "Odaburu Pureto" }, price: 250, photo: "Ordövr Tabağı", ingredients: "" },
  { id: 2127, category: 'meze', name: { tr: "Arnavut Ciğeri", en: "Albanian-Style Liver", ja: "アルバニア風レバー", ja_latn: "Arubania-fu Reba" }, price: 232.5, photo: "Arnavut Ciğeri", ingredients: "" },
  { id: 2143, category: 'meze', name: { tr: "Yoğurt Kase", en: "Bowl of Yogurt", ja: "ヨーグルト", ja_latn: "Wan Yoguruto" }, price: 34, photo: "Yoğurt Kase", ingredients: "" },
  { id: 2326, category: 'meze', name: { tr: "Beyaz Peynir", en: "White Cheese", ja: "朝食用ホワイトチーズ", ja_latn: "Asagohan-yo Shiro Chizu" }, price: 59, photo: "Beyaz Peynir", ingredients: "" },
  { id: 2012, category: 'pideLahmacun', name: { tr: "Lahmacun Klasik", en: "Classic Lahmacun", ja: "ラフマジュン クラシック", ja_latn: "Ramajon Kurashikku" }, price: 72, photo: "Lahmacun Klasik", ingredients: "" },
  { id: 2018, category: 'pideLahmacun', name: { tr: "Kıymalı Pide", en: "Minced Meat Pide", ja: "挽肉入りピデ", ja_latn: "Hikiniku no Pide" }, price: 130.5, photo: "Kıymalı Pide", ingredients: "" },
  { id: 2027, category: 'pideLahmacun', name: { tr: "Karışık Pide", en: "Mixed Pide", ja: "ミックスピデ", ja_latn: "Mikkusu Pide" }, price: 201.5, photo: "Karışık Pide", ingredients: "" },
  { id: 2028, category: 'pideLahmacun', name: { tr: "Kuşbaşı Pide", en: "Diced Meat Pide", ja: "角切り肉入りピデ", ja_latn: "Kakugiri Niku no Pide" }, price: 212, photo: "Kuşbaşı Pide", ingredients: "" },
  { id: 2036, category: 'pideLahmacun', name: { tr: "Lahmacun Antep Usulü", en: "Antep-Style Lahmacun", ja: "ガズィアンテプ風ラフマジュン", ja_latn: "Ramajon Antep-fu" }, price: 72.5, photo: "Lahmacun Antep Usulü", ingredients: "" },
  { id: 2043, category: 'pideLahmacun', name: { tr: "Üç Peynirli Pide", en: "Three-Cheese Pide", ja: "3種のチーズ入りピデ", ja_latn: "San-shurui no Chizu Pide" }, price: 160, photo: "Üç Peynirli Pide", ingredients: "" },
  { id: 2072, category: 'pideLahmacun', name: { tr: "Kaşarlı Pide", en: "Cheese Pide", ja: "チーズ入りピデ", ja_latn: "Chizu Pide" }, price: 106, photo: "Kaşarlı Pide", ingredients: "" },
  { id: 2123, category: 'pideLahmacun', name: { tr: "Kavurmalı Pide", en: "Pide with Roasted Meat", ja: "肉炒め入りピデ", ja_latn: "Niku Itame Pide" }, price: 392.5, photo: "Kavurmalı Pide", ingredients: "" },
  { id: 2031, category: 'pizza', name: { tr: "Pizza Karışık", en: "Mixed Pizza", ja: "ミックスピザ", ja_latn: "Mikkusu Piza" }, price: 165, photo: "Pizza Karışık", ingredients: "" },
  { id: 2090, category: 'pizza', name: { tr: "Pizza Margarita", en: "Margherita Pizza", ja: "マルゲリータピザ", ja_latn: "Marugerita Piza" }, price: 75, photo: "Pizza Margarita", ingredients: "" },
  { id: 2109, category: 'pizza', name: { tr: "Pizza Turko", en: "Pizza Turko", ja: "ピザ・トゥルコ", ja_latn: "Piza Turuko" }, price: 230, photo: "Pizza Turko", ingredients: "" },
  { id: 2131, category: 'pizza', name: { tr: "Pizza Corolla Ateşi Acılı", en: "Spicy Corolla Fire Pizza", ja: "辛口カローラ・ファイヤーピザ", ja_latn: "Karai Karora no Honoo Piza" }, price: 424, photo: "Pizza Corolla Ateşi Acılı", ingredients: "" },
  { id: 2015, category: 'salads', name: { tr: "Mevsim Salata", en: "Seasonal Salad", ja: "季節のサラダ", ja_latn: "Kisetsu no Sarada" }, price: 50, photo: "Mevsim Salata", ingredients: "" },
  { id: 2021, category: 'salads', name: { tr: "Peynirli Mevsim Salata", en: "Seasonal Salad with Cheese", ja: "チーズ入り季節のサラダ", ja_latn: "Chizu to Kisetsu no Sarada" }, price: 75, photo: "Peynirli Mevsim Salata", ingredients: "" },
  { id: 2057, category: 'salads', name: { tr: "Çoban Salata", en: "Shepherd's Salad", ja: "羊飼いのサラダ", ja_latn: "Choban Sarada" }, price: 40.25, photo: "Çoban Salata", ingredients: "" },
  { id: 2062, category: 'salads', name: { tr: "Peynirli Çoban Salata", en: "Shepherd's Salad with Cheese", ja: "チーズ入り羊飼いのサラダ", ja_latn: "Chizu Choban Sarada" }, price: 57, photo: "Peynirli Çoban Salata", ingredients: "" },
  { id: 2071, category: 'salads', name: { tr: "Gavurdağı Salata", en: "Gavurdağı Salad", ja: "ガヴルダー・サラダ", ja_latn: "Gavurudagi Sarada" }, price: 116, photo: "Gavurdağı Salata", ingredients: "" },
  { id: 2119, category: 'salads', name: { tr: "Söğüş Salata", en: "Fresh Vegetable Salad", ja: "生野菜サラダ", ja_latn: "Nama Yasai Sarada" }, price: 43.5, photo: "Söğüş Salata", ingredients: "" },
  { id: 2163, category: 'salads', name: { tr: "Göbek Salata", en: "Lettuce Salad", ja: "レタスサラダ", ja_latn: "Reタsu Sarada" }, price: 72, photo: "Göbek Salata", ingredients: "" },
  { id: 2173, category: 'wines', name: { tr: "Beyaz Çankaya 37,5 cl", en: "Çankaya White Wine 37.5 cl", ja: "チャンカヤ 白ワイン 37.5センチリットル", ja_latn: "Shiro Chankaya 37.5 Sentorittoru" }, price: 565.5, photo: "Beyaz Çankaya 37,5 cl", ingredients: "" },
  { id: 2187, category: 'wines', name: { tr: "Kırmızı Yakut 75 cl", en: "Yakut Red Wine 75 cl", ja: "ヤクート 赤ワイン 75センチリットル", ja_latn: "Aka Yakuto 75 Sentorittoru" }, price: 1166.5, photo: "Kırmızı Yakut 75 cl", ingredients: "" },
  { id: 2193, category: 'wines', name: { tr: "Kırmızı Villa Doluca 37,5 cl", en: "Villa Doluca Red Wine 37.5 cl", ja: "ヴィラ・ドルジャ 赤ワイン 37.5センチリットル", ja_latn: "Aka Vira Doruka 37.5 Sentorittoru" }, price: 457.5, photo: "Kırmızı Villa Doluca 37,5 cl", ingredients: "" },
  { id: 2194, category: 'wines', name: { tr: "Kırmızı Villa Doluca 75 cl", en: "Villa Doluca Red Wine 75 cl", ja: "ヴィラ・ドルジャ 赤ワイン 75センチリットル", ja_latn: "Aka Vira Doruka 75 Sentorittoru" }, price: 744.5, photo: "Kırmızı Villa Doluca 75 cl", ingredients: "" },
  { id: 2195, category: 'wines', name: { tr: "Beyaz Sarafin Sauvignon Blanc 75 cl", en: "Sarafin Sauvignon Blanc White Wine 75 cl", ja: "サラフィン ソーヴィニヨン・ブラン 白ワイン 75センチリットル", ja_latn: "Shiro Sarafin Sovinyon Buran 75 Sentorittoru" }, price: 1238.5, photo: "Beyaz Sarafin Sauvignon Blanc 75 cl", ingredients: "" },
  { id: 2198, category: 'wines', name: { tr: "Kırmızı Angora 75 cl", en: "Angora Red Wine 75 cl", ja: "アンゴラ 赤ワイン 75センチリットル", ja_latn: "Aka Angora 75 Sentorittoru" }, price: 795.5, photo: "Kırmızı Angora 75 cl", ingredients: "" },
  { id: 2199, category: 'wines', name: { tr: "Kırmızı Sarafin Merlot 75 cl", en: "Sarafin Merlot Red Wine 75 cl", ja: "サラフィン メルロー 赤ワイン 75センチリットル", ja_latn: "Aka Sarafin Meruro 75 Sentorittoru" }, price: 1922.5, photo: "Kırmızı Sarafin Merlot 75 cl", ingredients: "" },
  { id: 2200, category: 'wines', name: { tr: "Kırmızı Yakut 37,5 cl", en: "Yakut Red Wine 37.5 cl", ja: "ヤクート 赤ワイン 37.5センチリットル", ja_latn: "Aka Yakuto 37.5 Sentorittoru" }, price: 601, photo: "Kırmızı Yakut 37,5 cl", ingredients: "" },
  { id: 2202, category: 'wines', name: { tr: "Beyaz Angora 75 cl", en: "Angora White Wine 75 cl", ja: "アンゴラ 白ワイン 75センチリットル", ja_latn: "Shiro Angora 75 Sentorittoru" }, price: 899.4, photo: "Beyaz Angora 75 cl", ingredients: "" },
  { id: 2203, category: 'wines', name: { tr: "Beyaz Çankaya 18,75 cl", en: "Çankaya White Wine 18.75 cl", ja: "チャンカヤ 白ワイン 18.75センチリットル", ja_latn: "Shiro Chankaya 18.75 Sentorittoru" }, price: 312, photo: "Beyaz Çankaya 18,75 cl", ingredients: "" },
  { id: 2204, category: 'wines', name: { tr: "Beyaz Çankaya 75 cl", en: "Çankaya White Wine 75 cl", ja: "チャンカヤ 白ワイン 75センチリットル", ja_latn: "Shiro Chankaya 75 Sentorittoru" }, price: 979, photo: "Beyaz Çankaya 75 cl", ingredients: "" },
  { id: 2206, category: 'wines', name: { tr: "Beyaz Sarafin Chardonnay 75 cl", en: "Sarafin Chardonnay White Wine 75 cl", ja: "サラフィン シャルドネ 白ワイン 75センチリットル", ja_latn: "Shiro Sarafin Sharudone 75 Sentorittoru" }, price: 1922.5, photo: "Beyaz Sarafin Chardonnay 75 cl", ingredients: "" },
  { id: 2208, category: 'wines', name: { tr: "Beyaz Villa Doluca 75 cl", en: "Villa Doluca White Wine 75 cl", ja: "ヴィラ・ドルジャ 白ワイン 75センチリットル", ja_latn: "Shiro Vira Doruka 75 Sentorittoru" }, price: 912, photo: "Beyaz Villa Doluca 75 cl", ingredients: "" },
  { id: 2211, category: 'wines', name: { tr: "Kırmızı Angora 37,5 cl", en: "Angora Red Wine 37.5 cl", ja: "アンゴラ 赤ワイン 37.5センチリットル", ja_latn: "Aka Angora 37.5 Sentorittoru" }, price: 494, photo: "Kırmızı Angora 37,5 cl", ingredients: "" },
  { id: 2212, category: 'wines', name: { tr: "Kırmızı Yakut 18,75 cl", en: "Yakut Red Wine 18.75 cl", ja: "ヤクート 赤ワイン 18.75センチリットル", ja_latn: "Aka Yakuto 18.75 Sentorittoru" }, price: 329, photo: "Kırmızı Yakut 18,75 cl", ingredients: "" },
  { id: 2221, category: 'wines', name: { tr: "Beyaz Angora 37,5 cl", en: "Angora White Wine 37.5 cl", ja: "アンゴラ 白ワイン 37.5センチリットル", ja_latn: "Shiro Angora 37.5 Sentorittoru" }, price: 494, photo: "Beyaz Angora 37,5 cl", ingredients: "" },
  { id: 2222, category: 'wines', name: { tr: "Beyaz Villa Doluca 37,5 cl", en: "Villa Doluca White Wine 37.5 cl", ja: "ヴィラ・ドルジャ 白ワイン 37.5センチリットル", ja_latn: "Shiro Vira Doruka 37.5 Sentorittoru" }, price: 457.5, photo: "Beyaz Villa Doluca 37,5 cl", ingredients: "" },
  { id: 2016, category: 'hotDrinks', name: { tr: "Bardak Çay", en: "Glass of Tea", ja: "グラス紅茶", ja_latn: "Koppu no Kocha" }, price: 10, photo: "Bardak Çay", ingredients: "" },
  { id: 2032, category: 'hotDrinks', name: { tr: "Türk Kahvesi", en: "Turkish Coffee", ja: "トルココーヒー", ja_latn: "Toruko Kohi" }, price: 20, photo: "Türk Kahvesi", ingredients: "" },
  { id: 2129, category: 'hotDrinks', name: { tr: "Fincan Çay", en: "Cup of Tea", ja: "カップ紅茶", ja_latn: "Kappu no Kocha" }, price: 11.25, photo: "Fincan Çay", ingredients: "" },
  { id: 2138, category: 'hotDrinks', name: { tr: "Sütlü Kahve Jacobs", en: "Jacobs Coffee with Milk", ja: "ジャコブス ミルクコーヒー", ja_latn: "Miruku Kohi Jakobbuzu" }, price: 19, photo: "Sütlü Kahve Jacobs", ingredients: "" },
  { id: 2166, category: 'hotDrinks', name: { tr: "Sade Kahve Jacobs", en: "Jacobs Black Coffee", ja: "ジャコブス ブラックコーヒー", ja_latn: "Puren Kohi Jakobbuzu" }, price: 16, photo: "Sade Kahve Jacobs", ingredients: "" },
  { id: 2168, category: 'hotDrinks', name: { tr: "Sıcak Çikolata Jacobs", en: "Jacobs Hot Chocolate", ja: "ジャコブス ホットチョコレート", ja_latn: "Hotto Chokoreto Jakobbuzu" }, price: 13.5, photo: "Sıcak Çikolata Jacobs", ingredients: "" },
  { id: 2013, category: 'coldDrinks', name: { tr: "İçim Ayran 285 ml", en: "İçim Ayran 285 ml", ja: "イチム・アイラン 285ミリリットル", ja_latn: "Ichimu Airan 285 Miririttoru" }, price: 20, photo: "İçim Ayran 285 ml", ingredients: "" },
  { id: 2014, category: 'coldDrinks', name: { tr: "Coca Cola 250 ml", en: "Coca-Cola 250 ml", ja: "コカ・コーラ 250ミリリットル", ja_latn: "Koka Kora 250 Miririttoru" }, price: 45, photo: "Coca Cola 250 ml", ingredients: "" },
  { id: 2029, category: 'coldDrinks', name: { tr: "Lipton Ice Tea Şeftali 330 ml", en: "Lipton Ice Tea Peach 330 ml", ja: "リプトン アイスティー ピーチ 330ミリリットル", ja_latn: "Riputon Aisu Ti Pichi 330 Miririttoru" }, price: 38.5, photo: "Lipton Ice Tea Şeftali 330 ml", ingredients: "" },
  { id: 2033, category: 'coldDrinks', name: { tr: "Sade Soda 200 ml", en: "Plain Mineral Water 200 ml", ja: "プレーンソーダ 200ミリリットル", ja_latn: "Puren Soda 200 Miririttoru" }, price: 14, photo: "Sade Soda 200 ml", ingredients: "" },
  { id: 2034, category: 'coldDrinks', name: { tr: "Cappy Meyve Suyu 330 ml", en: "Cappy Fruit Juice 330 ml", ja: "キャッピー フルーツジュース 330ミリリットル", ja_latn: "Kyappi Furutsu Jusu 330 Miririttoru" }, price: 47.75, photo: "Cappy Meyve Suyu 330 ml", ingredients: "" },
  { id: 2040, category: 'coldDrinks', name: { tr: "Şalgam Suyu 300 ml", en: "Turnip Juice 300 ml", ja: "シャルガムジュース 300ミリリットル", ja_latn: "Sharugamu Jusu 300 Miririttoru" }, price: 25, photo: "Şalgam Suyu 300 ml", ingredients: "" },
  { id: 2042, category: 'coldDrinks', name: { tr: "Pepsi Cola 330 ml", en: "Pepsi Cola 330 ml", ja: "ペプシコーラ 330ミリリットル", ja_latn: "Peputshi Kora 330 Miririttoru" }, price: 45.5, photo: "Pepsi Cola 330 ml", ingredients: "" },
  { id: 2044, category: 'coldDrinks', name: { tr: "Fanta 250 ml", en: "Fanta 250 ml", ja: "ファンタ 250ミリリットル", ja_latn: "Fanta 250 Miririttoru" }, price: 45.5, photo: "Fanta 250 ml", ingredients: "" },
  { id: 2050, category: 'coldDrinks', name: { tr: "Sprite Sade Gazoz 250 ml", en: "Sprite 250 ml", ja: "スプライト プレーンソーダ 250ミリリットル", ja_latn: "Supuraito Puren Soda 250 Miririttoru" }, price: 45.5, photo: "Sprite Sade Gazoz 250 ml", ingredients: "" },
  { id: 2058, category: 'coldDrinks', name: { tr: "Coca Cola Zero 250 ml", en: "Coca-Cola Zero 250 ml", ja: "コカ・コーラ ゼロ 250ミリリットル", ja_latn: "Koka Kora Zero 250 Miririttoru" }, price: 45.5, photo: "Coca Cola Zero 250 ml", ingredients: "" },
  { id: 2075, category: 'coldDrinks', name: { tr: "Lipton Ice Tea Limon 330 ml", en: "Lipton Ice Tea Lemon 330 ml", ja: "リプトン アイスティー レモン 330ミリリットル", ja_latn: "Riputon Aisu Ti Remon 330 Miririttoru" }, price: 38, photo: "Lipton Ice Tea Limon 330 ml", ingredients: "" },
  { id: 2077, category: 'coldDrinks', name: { tr: "Red Bull Enerji İçeceği 250 ml", en: "Red Bull Energy Drink 250 ml", ja: "レッドブル エナジードリンク 250ミリリットル", ja_latn: "Reddo Buru Enerugi Dorinku 250 Miririttoru" }, price: 100.5, photo: "Red Bull Enerji İçeceği 250 ml", ingredients: "" },
  { id: 2104, category: 'coldDrinks', name: { tr: "Coca Cola Zero 330 ml", en: "Coca-Cola Zero 330 ml", ja: "コカ・コーラ ゼロ 330ミリリットル", ja_latn: "Koka Kora Zero 330 Miririttoru" }, price: 50, photo: "Coca Cola Zero 330 ml", ingredients: "" },
  { id: 2106, category: 'coldDrinks', name: { tr: "Fruitti Soda Limonlu C-Max 200 ml", en: "Fruitti Lemon Soda C-Max 200 ml", ja: "フルッティ レモンソーダ C-Max 200ミリリットル", ja_latn: "Furuiti Remon Soda C-Max 200 Miririttoru" }, price: 21.75, photo: "Fruitti Soda Limonlu C-Max 200 ml", ingredients: "" },
  { id: 2133, category: 'coldDrinks', name: { tr: "Uludağ Limonata", en: "Uludağ Lemonade", ja: "ウルダー・レモネード", ja_latn: "Urudaa Remonedo" }, price: 30, photo: "Uludağ Limonata", ingredients: "" },
  { id: 2384, category: 'coldDrinks', name: { tr: "Şıra 250 ml", en: "Şıra", ja: "シラ", ja_latn: "Shira" }, price: 70, photo: "Şıra 250 ml", ingredients: "" },
  { id: 2148, category: 'coldDrinks', name: { tr: "Uludağ Şekersiz 250 ml", en: "Uludağ Sugar-Free 250 ml", ja: "ウルダー シュガーフリー 250ミリリットル", ja_latn: "Urudaa Shuga Resu 250 Miririttoru" }, price: 43.5, photo: "Uludağ Şekersiz 250 ml", ingredients: "" },
  { id: 2151, category: 'coldDrinks', name: { tr: "Uludağ Efsane Sade Gazoz 330 ml", en: "Uludağ Efsane Plain Soda 330 ml", ja: "ウルダー エフサネ プレーンソーダ 330ミリリットル", ja_latn: "Urudaa Densetsu no Puren Soda 330 Miririttoru" }, price: 43.5, photo: "Uludağ Efsane Sade Gazoz 330 ml", ingredients: "" },
  { id: 2152, category: 'coldDrinks', name: { tr: "Uludağ Portakallı 250 ml", en: "Uludağ Orange 250 ml", ja: "ウルダー オレンジ 250ミリリットル", ja_latn: "Urudaa Orenji 250 Miririttoru" }, price: 43.5, photo: "Uludağ Portakallı 250 ml", ingredients: "" },
  { id: 2155, category: 'coldDrinks', name: { tr: "Uludağ Efsane Portakallı Gazoz 330 ml", en: "Uludağ Efsane Orange Soda 330 ml", ja: "ウルダー エフサネ オレンジソーダ 330ミリリットル", ja_latn: "Urudaa Densetsu no Orenji Soda 330 Miririttoru" }, price: 43.5, photo: "Uludağ Efsane Portakallı Gazoz 330 ml", ingredients: "" },
  { id: 2156, category: 'coldDrinks', name: { tr: "Coca Cola cam şişe 250 ml", en: "Coca-Cola Glass Bottle 250 ml", ja: "コカ・コーラ ガラス瓶 250ミリリットル", ja_latn: "Koka Kora Garasu Bin 250 Miririttoru" }, price: 37.25, photo: "Coca Cola cam şişe 250 ml", ingredients: "" },
  { id: 2178, category: 'coldDrinks', name: { tr: "Fruitti Soda Kivili C-Max 200 Ml", en: "Fruitti Kiwi Soda C-Max 200 ml", ja: "フルッティ キウイソーダ C-Max 200ミリリットル", ja_latn: "Furuiti Kiwi Soda C-Max 200 Miririttoru" }, price: 21.75, photo: "Fruitti Soda Kivili C-Max 200 Ml", ingredients: "" },
  { id: 2189, category: 'coldDrinks', name: { tr: "Fanta Cam şişe 250 ml", en: "Fanta Glass Bottle 250 ml", ja: "ファンタ ガラス瓶 250ミリリットル", ja_latn: "Fanta Garasu Bin 250 Miririttoru" }, price: 37, photo: "Fanta Cam şişe 250 ml", ingredients: "" },
  { id: 1795, category: 'coldDrinks', name: { tr: "Limonata", en: "Lemonade", ja: "レモネード", ja_latn: "Remonedo" }, price: 45, photo: "Limonata", ingredients: "" },
  { id: 2393, category: 'coldDrinks', name: { tr: "Pepsi Cam Şişe 250 ml", en: "Pepsi Glass Bottle 250 ml", ja: "ペプシ ガラス瓶 250ml", ja_latn: "Pepushi Garasu Bin 250 ml" }, price: 33, photo: "Pepsi Cam Şişe 250 ml", ingredients: "" },
  { id: 2394, category: 'coldDrinks', name: { tr: "Uludağ Gazoz Cam Şişe 250 ml", en: "Uludağ Soda Glass Bottle 250 ml", ja: "ウルダー ガゾズ ガラス瓶 250ml", ja_latn: "Urudā Gazozu Garasu Bin 250 ml" }, price: 41, photo: "Uludağ Gazoz Cam Şişe 250 ml", ingredients: "" },
  { id: 2395, category: 'coldDrinks', name: { tr: "Yedigün Cam Şişe 250 ml", en: "Yedigün Glass Bottle 250 ml", ja: "イェディギュン ガラス瓶 250ml", ja_latn: "Yedigyun Garasu Bin 250 ml" }, price: 33, photo: "Yedigün Cam Şişe 250 ml", ingredients: "" },
  { id: 2023, category: 'special', name: { tr: "Corolla Special", en: "Corolla Special", ja: "カローラ・スペシャル", ja_latn: "Karora Supesharu" }, price: 380, photo: "Corolla Special", ingredients: "" },
  { id: 2047, category: 'special', name: { tr: "Lokum Bonfile", en: "Lokum Tenderloin", ja: "ロクム風ヒレ肉", ja_latn: "Rokumu Hire" }, price: 594.5, photo: "Lokum Bonfile", ingredients: "" },
  { id: 2060, category: 'special', name: { tr: "Tavuk Fajita", en: "Chicken Fajita", ja: "チキンファヒータ", ja_latn: "Chikin Fahita" }, price: 174, photo: "Tavuk Fajita", ingredients: "" },
  { id: 2063, category: 'special', name: { tr: "Bonfile Fajita", en: "Tenderloin Fajita", ja: "ヒレ肉ファヒータ", ja_latn: "Hire Fahita" }, price: 460, photo: "Bonfile Fajita", ingredients: "" },
  { id: 2084, category: 'special', name: { tr: "Tavuk A La King", en: "Chicken à la King", ja: "チキン・ア・ラ・キング", ja_latn: "Chikin A Ra Kingu" }, price: 190, photo: "Tavuk A La King", ingredients: "" },
  { id: 2085, category: 'special', name: { tr: "Çin Usulü Tavuk", en: "Chinese-Style Chicken", ja: "中華風チキン", ja_latn: "Chugoku-fu Chikin" }, price: 155, photo: "Çin Usulü Tavuk", ingredients: "" },
  { id: 2094, category: 'special', name: { tr: "Meksika Usulü Tavuk", en: "Mexican-Style Chicken", ja: "メキシコ風チキン", ja_latn: "Mekishiko-fu Chikin" }, price: 233, photo: "Meksika Usulü Tavuk", ingredients: "" },
  { id: 2099, category: 'special', name: { tr: "Hardal Soslu Tavuk", en: "Chicken with Mustard Sauce", ja: "マスタードソースチキン", ja_latn: "Masutado Sosu Chikin" }, price: 241.5, photo: "Hardal Soslu Tavuk", ingredients: "" },
  { id: 2101, category: 'special', name: { tr: "Japon Usulü Tavuk Kızartma", en: "Japanese-Style Fried Chicken", ja: "日本風フライドチキン", ja_latn: "Nihon-fu Furaido Chikin" }, price: 129, photo: "Japon Usulü Tavuk Kızartma", ingredients: "" },
  { id: 2022, category: 'desserts', name: { tr: "Soğuk Baklava Fıstıklı (3 dilim)", en: "Cold Pistachio Baklava (3 Slices)", ja: "ピスタチオ入り冷製バクラヴァ（3切れ）", ja_latn: "Tsumetai Pisuta Bakurava (3 Kire)" }, price: 180, photo: "Soğuk Baklava Fıstıklı (3 dilim)", ingredients: "" },
  { id: 2045, category: 'desserts', name: { tr: "Baklava Fıstıklı (4 dilim)", en: "Pistachio Baklava (4 Slices)", ja: "ピスタチオ入りバクラヴァ（4切れ）", ja_latn: "Pisuta Bakurava (4 Kire)" }, price: 140.5, photo: "Baklava Fıstıklı (4 dilim)", ingredients: "" },
  { id: 1633, category: 'desserts', name: { tr: "Trileçe", en: "Trileçe", ja: "トリレチェ", ja_latn: "Torireche" }, price: 90, photo: "Trileçe", ingredients: "" },
  { id: 2066, category: 'desserts', name: { tr: "Künefe Klasik Peynirli", en: "Classic Cheese Künefe", ja: "クラシックチーズ・キュネフェ", ja_latn: "Kurashikku Chizu Kunefe" }, price: 116.5, photo: "Künefe Klasik Peynirli", ingredients: "" },
  { id: 2068, category: 'desserts', name: { tr: "Kabak Tatlısı(Kaymak-Ceviz)", en: "Pumpkin Dessert with Clotted Cream and Walnuts", ja: "カボチャのデザート（カイマク・クルミ添え）", ja_latn: "Kabocha no Dezato (Kaymaku to Kurumi)" }, price: 120, photo: "Kabak Tatlısı(Kaymak-Ceviz)", ingredients: "" },
  { id: 2070, category: 'desserts', name: { tr: "CheeseCake Frambuaz", en: "Raspberry Cheesecake", ja: "ラズベリーチーズケーキ", ja_latn: "Rasuberi Chizukeki" }, price: 144, photo: "CheeseCake Frambuaz", ingredients: "" },
  { id: 2073, category: 'desserts', name: { tr: "Hasır Künefe Fıstıklı Kaymaklı", en: "Pistachio Künefe with Clotted Cream", ja: "ピスタチオとカイマクのハスル・キュネフェ", ja_latn: "Pisuta to Kaymaku no Hasiru Kunefe" }, price: 180, photo: "Hasır Künefe Fıstıklı Kaymaklı", ingredients: "" },
  { id: 1656, category: 'desserts', name: { tr: "Tiramusu", en: "Tiramisu", ja: "ティラミス", ja_latn: "Tiramisu" }, price: 126.75, photo: "Tiramusu", ingredients: "" },
  { id: 2082, category: 'desserts', name: { tr: "Meyve Tabağı Mevsimsel", en: "Seasonal Fruit Platter", ja: "季節のフルーツ盛り合わせ", ja_latn: "Kisetsu no Furutsu Pureto" }, price: 60, photo: "Meyve Tabağı Mevsimsel", ingredients: "" },
  { id: 2083, category: 'desserts', name: { tr: "CheeseCake Çikolata", en: "Chocolate Cheesecake", ja: "チョコレートチーズケーキ", ja_latn: "Chokoreto Chizukeki" }, price: 144, photo: "CheeseCake Çikolata", ingredients: "" },
  { id: 1667, category: 'desserts', name: { tr: "Katmer", en: "Katmer", ja: "カトメル", ja_latn: "Katomeru" }, price: 162.5, photo: "Katmer", ingredients: "" },
  { id: 2096, category: 'desserts', name: { tr: "Fıstık Rüyası", en: "Pistachio Dream", ja: "ピスタチオの夢", ja_latn: "Pisuta no Yume" }, price: 157.5, photo: "Fıstık Rüyası", ingredients: "" },
  { id: 2102, category: 'desserts', name: { tr: "Vanilyalı Lotuslu Puding", en: "Vanilla Lotus Pudding", ja: "バニラ・ロータスプディング", ja_latn: "Banira Rotasu Pudingu" }, price: 65, photo: "Vanilyalı Lotuslu Puding", ingredients: "" },
  { id: 2108, category: 'desserts', name: { tr: "Karamelli Fırın Sütlaç", en: "Caramelized Baked Rice Pudding", ja: "キャラメル焼きライスプディング", ja_latn: "Kyarameru Yaki Raisu Pudingu" }, price: 66.5, photo: "Karamelli Fırın Sütlaç", ingredients: "" },
  { id: 2121, category: 'desserts', name: { tr: "Ayva Tatlısı", en: "Quince Dessert", ja: "マルメロのデザート", ja_latn: "Marumero no Dezato" }, price: 113, photo: "Ayva Tatlısı", ingredients: "" },
  { id: 2213, category: 'desserts', name: { tr: "Maraş Usulü Kesme Dondurma", en: "Maraş-Style Cut Ice Cream", ja: "マラシュ風カットアイスクリーム", ja_latn: "Marashu-fu Kattobun Aisukurimu" }, price: 85, photo: "Maraş Usulü Kesme Dondurma", ingredients: "" },
  { id: 2219, category: 'desserts', name: { tr: "Soslu Dondurmalı Meyve", en: "Fruit with Sauce and Ice Cream", ja: "ソースとアイスクリーム添えフルーツ", ja_latn: "Sosu to Aisukurimu no Furutsu" }, price: 89.5, photo: "Soslu Dondurmalı Meyve", ingredients: "" },
  { id: 2422, category: 'desserts', name: { tr: "CheeseCake Limon", en: "Lemon Cheesecake", ja: "レモンチーズケーキ", ja_latn: "Remon Chīz kēki" }, price: 135.5, photo: "CheeseCake Limon", ingredients: "" },
  { id: 2149, category: 'whiskies', name: { tr: "Chivas Regal Duble", en: "Chivas Regal Double", ja: "シーバスリーガル ダブル", ja_latn: "Shivasu Rigaru Daburu" }, price: 350, photo: "Chivas Regal Duble", ingredients: "" },
  { id: 2157, category: 'whiskies', name: { tr: "Jack Daniels Duble", en: "Jack Daniel's Double", ja: "ジャックダニエル ダブル", ja_latn: "Jakku Danieruzu Daburu" }, price: 315.5, photo: "Jack Daniels Duble", ingredients: "" },
  { id: 2160, category: 'whiskies', name: { tr: "Chivas Regal Tek", en: "Chivas Regal Single", ja: "シーバスリーガル シングル", ja_latn: "Shivasu Rigaru Shinguru" }, price: 175, photo: "Chivas Regal Tek", ingredients: "" },
  { id: 2161, category: 'whiskies', name: { tr: "Johnnie Walker Red Label Duble", en: "Johnnie Walker Red Label Double", ja: "ジョニーウォーカー レッドラベル ダブル", ja_latn: "Joni Woka Reddo Reberu Daburu" }, price: 221.5, photo: "Johnnie Walker Red Label Duble", ingredients: "" },
  { id: 2171, category: 'whiskies', name: { tr: "Jack Daniels Tek", en: "Jack Daniel's Single", ja: "ジャックダニエル シングル", ja_latn: "Jakku Danieruzu Shinguru" }, price: 159, photo: "Jack Daniels Tek", ingredients: "" },
  { id: 2172, category: 'whiskies', name: { tr: "J Viski Tek", en: "J Whisky Single", ja: "Jウイスキー シングル", ja_latn: "Jei Uisuki Shinguru" }, price: 103, photo: "J Viski Tek", ingredients: "" },
  { id: 2183, category: 'whiskies', name: { tr: "Chivas Regal 70 cl", en: "Chivas Regal 70 cl", ja: "シーバスリーガル 70センチリットル", ja_latn: "Shivasu Rigaru 70 Sentorittoru" }, price: 2919, photo: "Chivas Regal 70 cl", ingredients: "" },
  { id: 2186, category: 'whiskies', name: { tr: "J Viski Duble", en: "J Whisky Double", ja: "Jウイスキー ダブル", ja_latn: "Jei Uisuki Daburu" }, price: 207.5, photo: "J Viski Duble", ingredients: "" },
  { id: 2191, category: 'whiskies', name: { tr: "Jack Daniels 70 cl", en: "Jack Daniel's 70 cl", ja: "ジャックダニエル 70センチリットル", ja_latn: "Jakku Danieruzu 70 Sentorittoru" }, price: 2527, photo: "Jack Daniels 70 cl", ingredients: "" },
  { id: 2192, category: 'whiskies', name: { tr: "Johnnie Walker Red Label Tek –", en: "Johnnie Walker Red Label Single", ja: "ジョニーウォーカー レッドラベル シングル", ja_latn: "Joni Woka Reddo Reberu Shinguru" }, price: 111, photo: "Johnnie Walker Red Label Tek –", ingredients: "" },
  { id: 2197, category: 'whiskies', name: { tr: "Johnnie Walker Red Label 70 cl", en: "Johnnie Walker Red Label 70 cl", ja: "ジョニーウォーカー レッドラベル 70センチリットル", ja_latn: "Joni Woka Reddo Reberu 70 Sentorittoru" }, price: 1776.5, photo: "Johnnie Walker Red Label 70 cl", ingredients: "" },
  { id: 2210, category: 'whiskies', name: { tr: "J Viski 70 cl", en: "J Whisky 70 cl", ja: "Jウイスキー 70センチリットル", ja_latn: "Jei Uisuki 70 Sentorittoru" }, price: 1651.5, photo: "J Viski 70 cl", ingredients: "" },
  { id: 2069, category: 'oliveOil', name: { tr: "Zeytinyağlı Yaprak Sarma", en: "Stuffed Vine Leaves with Olive Oil", ja: "オリーブオイルのブドウ葉包み", ja_latn: "Oribu Oiru no Budou no Ha Tsutsumi" }, price: 70, photo: "Zeytinyağlı Yaprak Sarma", ingredients: "" },
  { id: 2088, category: 'oliveOil', name: { tr: "Zeytinyağlı Enginar", en: "Artichoke with Olive Oil", ja: "オリーブオイルのアーティチョーク", ja_latn: "Oribu Oiru no Aachichoku" }, price: 70, photo: "Zeytinyağlı Enginar", ingredients: "" },
  { id: 2095, category: 'oliveOil', name: { tr: "Zeytinyağlı Patlıcan Salata", en: "Eggplant Salad with Olive Oil", ja: "オリーブオイルのナスサラダ", ja_latn: "Oribu Oiru no Nasu Sarada" }, price: 35, photo: "Zeytinyağlı Patlıcan Salata", ingredients: "" },
  { id: 2165, category: 'oliveOil', name: { tr: "Zeytinyağlı Taze Fasulye", en: "Green Beans with Olive Oil", ja: "オリーブオイルのインゲン豆", ja_latn: "Oribu Oiru no Ingenmame" }, price: 43, photo: "Zeytinyağlı Taze Fasulye", ingredients: "" }
];
